### ISSUE TITLE
Add better loading prompt on progress 

### ISSUE THREAD

**Issue by rickyyx** [8by8-org/web-app#102]
## Problem
When retrieving the badges info on the progress page. We are seeing this, we should have a better loading page similar to what we have in the `/voterreg` workflow. 
<img width="453" alt="image" src="https://user-images.githubusercontent.com/11676094/161396251-312bbbfd-fc71-4a3e-a243-4ef55dd84bfd.png">

E.g. some loading animation: 
![image](https://user-images.githubusercontent.com/11676094/161397324-aa68b9ba-545b-47af-bae2-6177b712919e.png)

## Additional context
Steps to reproduce: 
- Sign up a new account 
- Just before the `/progress` page gets loaded.

**Comment by dvorakjt** [comment]
Hi Ricky, once the voter reg PR is merged, the component for the loading indicator should be able to be imported elsewhere and used. I'm about to reply to your comment on that one so hopefully we can get that merged in the next day or so
