### ISSUE TITLE
NA days when first signed in 

### ISSUE THREAD

**Issue by rickyyx** [8by8-org/web-app#109]
## Problem

NA days left when first signed-up and logged in
![image](https://user-images.githubusercontent.com/11676094/162875811-fad00a78-2506-40ff-a09e-2126ca262fba.png)

## Additional context
Ways to reproduce: 
1. Sign up a new account 
2. NA is showing up when /progress page is firstly loaded.

**Comment by mnarayan1** [comment]
I had this problem too, but I think I resolved it in one of my PRs by including a longer loading time. I'm not able to replicate the bug now. Is this still an issue?

**Comment by rickyyx** [comment]
Yep, seems to be gone on the master branch for now. Closing.

**Comment by rickyyx** [comment]
Seems this is still showing up, at least in incognito mode?

Steps to reproduce: 
1. Register a new challenger account  in incognito mode at `/homepage`
2. The progress paging showing this:

<img width="490" alt="image" src="https://user-images.githubusercontent.com/11676094/166406441-fbcdeb3f-8e19-4c07-acaf-fb91360a6744.png">

**Comment by wcouturiaux** [comment]
Assuming this is on mobile -> is the styling/responsiveness issue documented? I belive the full thing is NAN and can't read Days left as it spills over to black on black.

**Comment by rickyyx** [comment]
Yeah, it is `NAN`, and we currently work with the assumption that the app will be primarily used on mobile. So making the app responsive will be something we are working on in beta maybe.
