### ISSUE TITLE
Fix underline rendering issue

### ISSUE THREAD

**Issue by rickyyx** [8by8-org/web-app#122]
## Problem
Underline effect doesn't render well on the website sometimes. Need to figure out why. 

## Goal 
<img width="635" alt="image" src="https://user-images.githubusercontent.com/11676094/166405175-304bae79-600f-445f-be30-2f50fbd8f90b.png">

## Additional context
I haven't found a consistent way of reproducing the this error also, but it shows up frequently enough. Would be great to understand why this happens and how to fix this.

**Comment by arniber21** [comment]
This might be it: https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip

**Comment by arniber21** [comment]
Using inspect element, just add `text-decoration-skip-ink: none;` to the code where we set the styles for underline

**Comment by arniber21** [comment]
This looks like it's fixed, mind if i close it?
