### ISSUE TITLE
Voter Registration No User Prompt for Invalid Street/Address

### ISSUE THREAD

**Issue by wcouturiaux** [8by8-org/web-app#128]
## Problem
During voter registration on HomeAddress if the user enters a wrong street address and clicks the Next button nothing happens.

## Goal 
Prompt User or highlight input that street address/address is invalid.

**Comment by arniber21** [comment]
On this issue - Do we want to check if the Address itself is real, or only that it is in a valid format? Looked into both - if we are just checking format, then we can do a simple regex fix. If we want to validate if an address is real, it takes a bit more work. A solution like this https://www.mapbox.com/address-autofill would be an option on that front.

**Comment by Devanshusp** [comment]
We want to check if the address exists so it doesn't create an error for the voter registration flow

I really like what you have suggested, considering it has a free tier that should be good for us for now.
![image](https://user-images.githubusercontent.com/66650721/172746746-9742c11e-2521-4375-9035-08507a3ea5c7.png)

**Comment by arniber21** [comment]
Some additional info on it - this could be very easy to set up. I'll see if I can get something working soon. https://docs.mapbox.com/mapbox-search-js/api/react/autofill/

**Comment by Devanshusp** [comment]
This task is on hold for now - won't need to use Mapbox if #155 works
