### ISSUE TITLE
[Bug] Fix Input Errors on SignupPage.js

### ISSUE THREAD

**Issue by wcouturiaux** [8by8-org/web-app#151]
## Problem

1. Add error logic to Re-Enter Email input.
2. When an input field is left blank, the red error styling and the original black both show. 
3. Error styling persists once user enters input

## Goal 
- [ ] 1. If Re-Enter Email field is blank when user submits form, red error styling should display.
- [ ] 2. *Double Check Figma* Red Lines should cover the black input line and red error text should be have space from black line(won't be present when adjusted)
- [ ] 3. *Confirm with Design* After an input error is present and a user enters text in that input, the error styling should clear. 

## Additional context
![Screen Shot 2022-07-02 at 1 39 27 PM](https://user-images.githubusercontent.com/37006112/177011176-b970c89b-a9d6-4982-8a38-cc722090424e.png)

**Comment by Devanshusp** [comment]
I believe this has been fixed - could always re-open if not
