### ISSUE TITLE
[US4.1] Add 8by8 partner data database

### ISSUE THREAD

**Issue by Devanshusp** [8by8-org/web-app#164]
## Problem
- Need a method to view (from the app) and update (from outside the app) the 8by8 partner database

## Goal 
- Implement a database for 8by8 partner data in firebase
- Build a way to access this data in the app

## Additional context
- Explore firebase firestore database vs firebase realtime database for this
- Should be made easy to update (anticipate updating data & partners leaving/joining)
- Link to data ([8by8 Partner Data - Google Sheets](https://docs.google.com/spreadsheets/d/1cNm8SzcTPgG1WYad8M2kT3QBJ9rQ8AdFBCvEkwkQ7Js/edit#gid=0)) <-- request access to this doc
- This document is still being updated

**Comment by MazharulIslam-Naim** [comment]
Functions that need to be added:

- [ ] Get every partner data.
- [ ] Get a specific partner data.

Only for admins:

- [ ] Write a new partner.
- [ ] Update a partner data.
- [ ] Delete a partner data.

**Comment by Devanshusp** [comment]
Completed with #175
