### ISSUE TITLE
[US4.2] Build /rewards page

### ISSUE THREAD

**Issue by Devanshusp** [8by8-org/web-app#165]
## Problem
- Need to show users what rewards are available for them completing their actions/challenges

## Goal 
- Build a /rewards page which shows 8by8 partners
- Link from sidebar
- ![image](https://user-images.githubusercontent.com/66650721/180670866-341dfc34-c4f8-4c47-9c62-b3f0d06bb93e.png)
- ![image](https://user-images.githubusercontent.com/66650721/180670876-93951755-fdf0-431c-b9c0-c977d9f260ab.png)

## Additional context
- This page should be easily customizable for future (anticipating partners joining & leaving)
- Also build a no partners version in case partners leave
- Get partner data from database (US4.1)
- Depends on completion of #164

**Comment by arniber21** [comment]
I think this can be closed?

**Comment by Devanshusp** [comment]
Yep, I'll close this
