### ISSUE TITLE
[US6.1/8.1] Build and implement /choosereward page for challenger & player

### ISSUE THREAD

**Issue by Devanshusp** [8by8-org/web-app#167]
## Problem
- We need to give rewards to challengers and players for completing the challenge
- A challenger will receive a reward for completing the challenge
- A player will receive a reward when their challenger completes the challenge
- A challenger reward is different than a player reward (a user who is both a challenger and a player can get 2 rewards)

## Goal 
- Build a /choosereward page that allows users to select their reward
- ![image](https://user-images.githubusercontent.com/66650721/180671739-a143f800-36fe-49f7-9308-7098a3f60baa.png)
- Challenger rewards should be displayed in /progress
- Player rewards should be displayed in /actions
- ![image](https://user-images.githubusercontent.com/66650721/180671707-6955e8cf-9ce3-4c33-ab6e-3e781de6f0f9.png)

## Additional context
- “Choose reward” button disappears once user selects their reward
- Will need to update the player's database with reward
- Get partner data from database (US4.1)
- Depends on completion of #164

**Comment by arniber21** [comment]
So this issue is partly complete with the latest PR - still some work to do on showing the code and all that

**Comment by Devanshusp** [comment]
Hey @arniber21, @rajnawal has started working on displaying the data & saving the rewards to the database

**Comment by arniber21** [comment]
Sounds great
