### ISSUE TITLE
Setup email trigger

### ISSUE THREAD

**Issue by rickyyx** [8by8-org/web-app#42]
## Problem
We need to notify users at various cases

## Goal 
Make a function that triggers to send an email if the following occurs
- When a challenger (or player) takes a challenge
- When a challenger earns a badge
- When a challenger wins (earns 8 badges)
- When a challenger doesn’t finish a challenge after 8 days
- When a player signs up
- When a challenger or player registers to vote
- When a challenger or players requests a PDF of their voter reg form
- When a player sets up an election reminder

Other
- Need to pull data (name, challenge days remaining, etc.) from backend and implement in email

## Additional context
Email templates at: https://www.figma.com/file/0Q2tpQqi9sYcIA3ZyiX3PF/8BY8_POD_Jul30?node-id=3442%3A53007

**Comment by rickyyx** [comment]
Hey @ty730 , how hard would it be to change the resolution of the banner for the email template so it is PC friendly as well?
![image](https://user-images.githubusercontent.com/11676094/166081494-1baace58-ec39-4f9c-8bf7-4b3935c7e7d1.png)

**Comment by ty730** [comment]
@[githubxxcc](https://github.com/githubxxcc) It probably shouldn't be too hard, but I don't have a PC, so what resolution would you recommend? I will look into this and see if I can borrow a PC to be able to adjust it well.

**Comment by rickyyx** [comment]
@ty730 Oh, I mean laptop, not PC specifically or web client on the laptop. Basically email client that's not on mobile resolution.

**Comment by ty730** [comment]
@[githubxxcc](https://github.com/githubxxcc) Oh I see, I will adjust the resolution for non-mobile devices
