### ISSUE TITLE
Update sharing card on “/invite” page

### ISSUE THREAD

**Issue by githubxxcc** [8by8-org/web-app#70]
## Goal 

- Allow users to download a set of pictures to share (Instagram sharing flow)
- Integrate the share card to “/actions” page (Player side sharing - US7.1)
- text (SMS) investigation: how to send a pre-filled message from browser

## Additional context
Images: https://imgur.com/a/h9KzG05

Beta: 

- Add a preview function that generates and shows the user the image they will share (the referral /player-welcome page with the challenger name)

**Comment by ty730** [comment]
Completed issue in this PR: https://github.com/8by8-org/web-app/pull/105
