### ISSUE TITLE
Award badges to challenger

### ISSUE THREAD

**Issue by githubxxcc** [8by8-org/web-app#71]
## Problem
Award badges to users based on action completion

## Goal 
Badge earning scenarios:
- user clicks on “share” button in /progress (user only has to click on a share button and doesn’t have to successfully send an invite)
- A player completes an action
- Challenger registers to vote

## Additional context
- The /progress page should be updated properly with additional

**Comment by rickyyx** [comment]
Closing the issue since it should be tracked in #97 now
