### ISSUE TITLE
Allow challenger to restart the challenge

### ISSUE THREAD

**Issue by githubxxcc** [8by8-org/web-app#73]
## Goal 
- If the challenger doesn’t complete a challenge in 8 days, they go on an “on-hold” state
- When the challenger returns to the /progress page while “on-hold,” they get a notification that allows them to “restart challenge”
- Restarting the challenge will simply add 8 days to the challenge and the challenger will still have their old badges

## Additional context
![image](https://user-images.githubusercontent.com/66650721/156111612-c7c9f687-e72c-42fc-8f49-f656000b14d6.png)

**Comment by rickyyx** [comment]
Done in https://github.com/8by8-org/web-app/pull/112
