### ISSUE TITLE
Update /actions page

### ISSUE THREAD

**Issue by rickyyx** [8by8-org/web-app#75]
## Goal 
- Fix the navigation bar (navigating to the correct pages when clicking on "Take Actions") 
- Add crowns to challenger emoji when player completes actions
- Update (show/remove) buttons based on completed actions
- Add sharing function when player completes actions
- Add “you are done” page for when a player completes all actions
- Add “see your challenge” link for challengers on this page

**Comment by MazharulIslam-Naim** [comment]
Can I grab this?

**Comment by MazharulIslam-Naim** [comment]
This is done.
