### ISSUE TITLE
Multiple challenger handling

### ISSUE THREAD

**Issue by Devanshusp** [8by8-org/web-app#93]
# Goal

If a player clicks on multiple challenger links, we need to save all those challengers to the player's account to reward the challengers on the player's action completion.

Potential solution: save challengers in an array in local storage for signed-out users

**Comment by rickyyx** [comment]
Discussed with @Devanshusp and @mnarayan1 offline. 

**For alpha**
- We will still save the challenger ids in firebase, this will happen when the player starts an action workflow (so the player is signed in) 
- The challenger's id will still be saved in local storage at `/playerwelcome`
- We will assume most recent challenger for attribution 

**For beta** 
- We might allow players to choose which challenger to attribute to 
- We might allow players to attribute to multiple challengers for a single action 
- TODO: discuss with the Design team on the specific workflows.
