### ISSUE TITLE
Players alternative workflows

### ISSUE THREAD

**Issue by Devanshusp** [8by8-org/web-app#94]
# Goal

Player could see their own challenge (US3.5) 
Player could see what’s the 8by8 challenge (US3.6)
Player could share their actions (routing only) (US3.7)

**Comment by rickyyx** [comment]
So for US3.7 (and US7), player sharing the challenge is a bit more complicated: 

1. The text on the sharing card is different from the challenger's sharing 
![image](https://user-images.githubusercontent.com/11676094/162107813-85d76164-c56f-484c-adfe-6c156e4e28e8.png)

2. Player could only see the "Share you action" once they have done an action 
3. The unique link generated should be the last challenger they have helped. If there are multiple challengers the player has helped, choose the most recent one for now
4. Player sharing should not trigger a new badge, that's different from challenger sharing (which will award a new badge)


Having said that, I think it is possible to reuse the sharing component here. But we need to add a few more states.
