### ISSUE TITLE
Identify when user successfully completes an action

### ISSUE THREAD

**Issue by Devanshusp** [8by8-org/web-app#97]
# Goal
Need to indentify in the code when the user successfully completes an action and implement the `completedAction` function to update the badges (#71).

4 actions include:
- signing up for election reminders (@dvorakjt)
- taking the challenge (@wcouturiaux)
- registering to vote (@dvorakjt)
- sharing challenge (as a challenger) (@wcouturiaux)

## completedAction function
This function will grant the challenger a badge when they (or a player invited on their behalf) completes an action.

To use this function, import the `completedAction` function from `src/functions/UserData.js`

## 5 Arguments
- completedAction("election reminders")
  - gives user a badge for signing up for election reminders
  - if user is a challenger, they don't get a badge
  - if user is a player & they haven't completed an action before, their challenger gets the player badge
- completedAction("take challenge")
  - gives user a badge for taking the challenge
  - if user is a challenger, they don't get a badge
  - if user is a player & they haven't completed an action before, their challenger gets the player badge
- completedAction("register to vote")
  - gives user a badge for registering to vote
  - if user is a challenger, they get a badge
  - if user is a player & they haven't completed an action before, their challenger gets the player badge
- completedAction("share challenge")
  - gives user a badge for sharing challenge
  - if user is a challenger, they get a badge
  - if user is a player, they don't get a badge
- completedAction("test add badge")
  - gives user a random badge for testing (will be removed in production)

**Comment by wcouturiaux** [comment]
Can I grab this task?

**Comment by dvorakjt** [comment]
Hi William, I'm going to be adding the completedAction function to the election reminders and voter registration flows as I'm currently working on those two features, but adding it the sign up and share flows seems to be up for grabs :) you may want to just check with Devanshu over slack
